// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    // About Me 페이지
    'about',

    // Projects 카테고리
    {
      type: 'category',
      label: 'Projects',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: 'E-commerce',
          items: [{ type: 'autogenerated', dirName: 'projects/project1' }],
        },
        {
          type: 'category',
          label: 'REGO',
          items: [{ type: 'autogenerated', dirName: 'projects/project2' }],
        }
      ],
    },
  ],
};

export default sidebars;
